# Generated by Django 4.0.6 on 2023-03-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_required',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=15)),
                ('isStudent', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='images/')),
                ('email', models.EmailField(max_length=30)),
                ('setID', models.CharField(max_length=9)),
                ('prn', models.CharField(max_length=11)),
                ('div', models.CharField(max_length=1)),
                ('course', models.CharField(max_length=10)),
                ('fullname', models.CharField(max_length=20)),
                ('subjectAlias', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
                ('subjectAlias', models.CharField(max_length=50)),
                ('readUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectAlias', models.CharField(max_length=10, unique=True)),
                ('students', models.ManyToManyField(related_name='subjects_enrolled', to='campus.student')),
                ('teacher', models.ManyToManyField(related_name='subjects_taught', to='campus.teachers')),
            ],
        ),
    ]
