# Generated by Django 4.1 on 2023-03-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_required',
            new_name='loginCrad',
        ),
    ]
