# Generated by Django 4.1 on 2023-03-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0002_rename_login_required_logincrad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.CharField(max_length=50),
        ),
    ]
