# Generated by Django 4.1 on 2023-03-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='+000000000000', max_length=13),
            preserve_default=False,
        ),
    ]
