# Generated by Django 4.1 on 2023-03-11 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0004_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30, null=True)),
                ('task', models.CharField(max_length=50, null=True)),
                ('desc', models.TextField(null=True)),
                ('time', models.DateField(null=True)),
                ('reminder', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='logincrad',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='logincrad',
            name='isStudent',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='logincrad',
            name='password',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='div',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fullname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='prn',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='setID',
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='subjectAlias',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjectAlias',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='subjectName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='empid',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='fullname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='readUrl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='subjectAlias',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
