# Generated by Django 4.1 on 2023-03-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0005_todo_student_address_student_dob_teachers_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='desc',
            field=models.CharField(max_length=100),
        ),
    ]
