# Generated by Django 4.1 on 2023-03-12 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0007_remove_subjects_students_remove_subjects_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='notesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=30)),
                ('originalName', models.CharField(max_length=50)),
                ('createdName', models.CharField(max_length=50)),
                ('fileLocation', models.CharField(max_length=50)),
                ('uploadedFor', models.CharField(max_length=20)),
                ('uploadedOn', models.DateTimeField()),
                ('uploadedBy', models.CharField(max_length=20)),
            ],
        ),
    ]
