# Generated by Django 4.1 on 2023-03-12 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0008_notesfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notesfile',
            name='uploadedOn',
            field=models.DateField(),
        ),
    ]
