# Generated by Django 4.1 on 2023-03-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0009_alter_notesfile_uploadedon'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sem',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subjects',
            name='subjectType',
            field=models.CharField(default='Base', max_length=50),
            preserve_default=False,
        ),
    ]
