# Generated by Django 4.1 on 2023-03-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0010_student_sem_subjects_subjecttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default=0, max_length=7),
            preserve_default=False,
        ),
    ]
