# Generated by Django 4.1 on 2023-03-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0011_student_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('divList', models.CharField(max_length=1, null=True)),
                ('sharedBy', models.CharField(max_length=50)),
                ('urlShared', models.TextField()),
                ('sheetName', models.TextField()),
            ],
        ),
    ]
