# Generated by Django 4.1 on 2023-03-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0014_remove_teachers_readurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='lectureMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('start', models.CharField(max_length=25)),
                ('end', models.CharField(max_length=25)),
                ('changedFor', models.CharField(max_length=25)),
            ],
        ),
    ]
